language: node_js

node_js:
  - 8
  - 10
  - 12
  - 13
  - 14

matrix:
  allow_failures:
    - node_js: 
      - 12
      - 13
      - 14


branches:
    except:
        - gh-pages
        - /^v\d+(\.\d+){2}/

before_install:
    - npm i -g npm

script:
    - npm run lint && npm test

after_script:
    - if [[ `node --version` == *v8* ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi

cache:
  directories:
    - node_modules
